### ISSUE TITLE
Publishing workflow does not handle directories

### ISSUE THREAD

**Issue by pandurand** [kubelt/web3-publish#27]
When there is a directory included the matching regex, this is the error I get:

```bash
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.handler (/home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/vendor/cli.js:6990:82)
    at /home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/node_modules/yargs/build/index.cjs:1:9052
    at j (/home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/node_modules/yargs/build/index.cjs:1:9021)
    at M.runCommand (/home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/node_modules/yargs/build/index.cjs:1:7206)
    at Jt.[runYargsParserAndExecuteCommands] (/home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/node_modules/yargs/build/index.cjs:1:55997)
    at M.parseAndUpdateUsage (/home/runner/work/_actions/kubelt/web3-publish/v0-pre-alpha/node_modules/yargs/build/index.cjs:1:7973) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
```

**Comment by alfl** [comment]
Upload with `as: "dir"` in the action's yaml config.
